# Generated by Django 4.1.6 on 2023-02-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Фамилия Имя')),
                ('stat_urv', models.TimeField(verbose_name='Начало УРВ')),
                ('fact_start', models.TimeField(verbose_name='Фактичесий приход')),
                ('being_late', models.TimeField(verbose_name='Опоздание')),
                ('end_urv', models.TimeField(verbose_name='Конец УРВ')),
                ('fact_end', models.TimeField(verbose_name='Фактический уход')),
                ('early_departure', models.TimeField(verbose_name='Ранний уход')),
                ('time_work', models.TimeField(verbose_name='Отработанное время')),
            ],
        ),
    ]
